- Use Bulma CSS for styling
- follow Vue3/ts best practices
- Our dexie database in `dexie/` is the single source of truth
- Components should be representational
- keep code unit-testable as much a possible
- fix linter errors always