# Generated by Django 6.0.6 on 2026-07-06 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('key', models.SlugField(max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('order', models.PositiveIntegerField(unique=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english', models.TextField()),
                ('english_credit', models.TextField()),
                ('cloze', models.TextField()),
                ('correct_answer', models.CharField(max_length=128)),
                ('wrong_answer', models.CharField(max_length=128)),
                ('german_credit', models.TextField()),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='saetze.lesson')),
            ],
            options={
                'ordering': ['lesson_id', 'id'],
            },
        ),
    ]
