# Generated by Django 6.0.6 on 2026-07-08 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comprehensible_input', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='code',
            field=models.CharField(default='', max_length=8, unique=True),
            preserve_default=False,
        ),
    ]
