export type TaskType = 
  | 'add-pronunciation' 
  | 'immersion-content'
  | 'free-translate'
  | 'add-sub-goals'
  | 'add-vocab-to-goal'
  | 'add-examples-to-goal'
  | 'add-milestones'
  | 'resource'
  | 'complete-goal'
  | 'milestone'