# Generated by Django 6.0.6 on 2026-07-04 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoardObject',
            fields=[
                ('slug', models.SlugField(max_length=64, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField(unique=True)),
                ('model_path', models.CharField(max_length=255)),
                ('hold_anchor_x', models.FloatField(blank=True, null=True)),
                ('hold_anchor_y', models.FloatField(blank=True, null=True)),
                ('hold_anchor_z', models.FloatField(blank=True, null=True)),
                ('hold_scale', models.FloatField(blank=True, null=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Locale',
            fields=[
                ('code', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='ObjectRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verb', models.CharField(max_length=64)),
                ('source_effect', models.CharField(choices=[('NOTHING', 'Nothing'), ('RETURN', 'Return'), ('DISAPPEAR', 'Disappear'), ('DESTRUCT', 'Destruct'), ('WIGGLE', 'Wiggle'), ('HELD', 'Held')], max_length=16)),
                ('target_effect', models.CharField(choices=[('NOTHING', 'Nothing'), ('RETURN', 'Return'), ('DISAPPEAR', 'Disappear'), ('DESTRUCT', 'Destruct'), ('WIGGLE', 'Wiggle'), ('HELD', 'Held')], max_length=16)),
                ('task_key', models.CharField(db_index=True, editable=False, max_length=160, unique=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relationships', to='tprboard.boardobject')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relationships', to='tprboard.boardobject')),
            ],
        ),
        migrations.CreateModel(
            name='SentenceFormulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('text', models.TextField()),
                ('locale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formulations', to='tprboard.locale')),
                ('relationship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formulations', to='tprboard.objectrelationship')),
            ],
            options={
                'ordering': ['relationship_id', 'locale_id', 'order'],
            },
        ),
        migrations.AddConstraint(
            model_name='objectrelationship',
            constraint=models.UniqueConstraint(fields=('source', 'target'), name='unique_relationship_per_pair'),
        ),
        migrations.AddConstraint(
            model_name='sentenceformulation',
            constraint=models.UniqueConstraint(fields=('locale', 'relationship', 'order'), name='unique_formulation_slot'),
        ),
    ]
