"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os

import dj_database_url
from dotenv import load_dotenv

load_dotenv('/etc/linguanodon.env')

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-wxk9t089lr2z0d%q0g+pc!vp4%r$$h8vakqms%a&o1@xj95di$')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'true').lower() == 'true'

ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'accounts',
    'core',
    'tprboard',
    'viettonepractice',
    'hebrewscript',
    'comprehensible_input',
    'arabicnumbers',
    'prepositions3d',
    'saetze',
    'egyptiansentences',
    'infinitesentences',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

if db_url := os.environ.get('DATABASE_URL'):
    DATABASES = {'default': dj_database_url.parse(db_url, conn_max_age=600)}
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

# tprboard's content (vocab/tasks/3D-object relationships) is read-only in
# normal operation, so it lives in its own committed SQLite file rather than
# the app's operational database. DATABASE_ROUTERS below routes the tprboard
# app's models here automatically.
DATABASES['tprboard'] = {
    'ENGINE': 'django.db.backends.sqlite3',
    'NAME': BASE_DIR / 'tprboard.sqlite3',
}

# viettonepractice's clip content (transcript + audio filename) is a fixed,
# randomly-sampled import from the listen-to-viet dataset - read-only in
# normal operation, so it lives in its own committed SQLite file. Routed here
# automatically by DATABASE_ROUTERS below.
DATABASES['viettonepractice'] = {
    'ENGINE': 'django.db.backends.sqlite3',
    'NAME': BASE_DIR / 'viettonepractice.sqlite3',
}

# hebrewscript's clip content (transcript + audio filename) is a fixed
# import from the learn-hebrew-script dataset - read-only in normal
# operation, so it lives in its own committed SQLite file. Routed here
# automatically by DATABASE_ROUTERS below.
DATABASES['hebrewscript'] = {
    'ENGINE': 'django.db.backends.sqlite3',
    'NAME': BASE_DIR / 'hebrewscript.sqlite3',
}

# comprehensible_input's Language/Video content is live, admin-managed CRUD
# data (unlike the read-only imported content of the apps above), so its
# sqlite file is not committed to git. Routed here automatically by
# DATABASE_ROUTERS below.
DATABASES['comprehensible_input'] = {
    'ENGINE': 'django.db.backends.sqlite3',
    'NAME': BASE_DIR / 'comprehensible_input.sqlite3',
}

# arabicnumbers's number/numeral/transliteration content is a fixed, small
# dataset - read-only in normal operation, so it lives in its own committed
# SQLite file. Routed here automatically by DATABASE_ROUTERS below.
DATABASES['arabicnumbers'] = {
    'ENGINE': 'django.db.backends.sqlite3',
    'NAME': BASE_DIR / 'arabicnumbers.sqlite3',
}

# prepositions3d's gloss/translation content (per-language sentences + audio
# paths) is a fixed import from the acquire-prepositions-3d dataset -
# read-only in normal operation, so it lives in its own committed SQLite
# file. Routed here automatically by DATABASE_ROUTERS below.
DATABASES['prepositions3d'] = {
    'ENGINE': 'django.db.backends.sqlite3',
    'NAME': BASE_DIR / 'prepositions3d.sqlite3',
}

# saetze's lesson/exercise content (German cloze-sentence drills with Tatoeba
# attribution) is a fixed import from the saetze dataset - read-only in
# normal operation, so it lives in its own committed SQLite file. Routed here
# automatically by DATABASE_ROUTERS below.
DATABASES['saetze'] = {
    'ENGINE': 'django.db.backends.sqlite3',
    'NAME': BASE_DIR / 'saetze.sqlite3',
}

# egyptiansentences's sentence/cloze-word content (Egyptian Arabic cloze
# drills from lisaanmasry.org, with precomputed distractors) is a fixed
# import from the basic-egyptian-sentences dataset - read-only in normal
# operation, so it lives in its own committed SQLite file. Routed here
# automatically by DATABASE_ROUTERS below.
DATABASES['egyptiansentences'] = {
    'ENGINE': 'django.db.backends.sqlite3',
    'NAME': BASE_DIR / 'egyptiansentences.sqlite3',
}

# infinitesentences's sentence/gloss content (vocabulary-in-context drills
# built from Tatoeba sentence pairs, across dozens of native/target language
# combinations) is a fixed import from the infinite-sentences-data dataset -
# read-only in normal operation, so it lives in its own committed SQLite
# file. Routed here automatically by DATABASE_ROUTERS below.
DATABASES['infinitesentences'] = {
    'ENGINE': 'django.db.backends.sqlite3',
    'NAME': BASE_DIR / 'infinitesentences.sqlite3',
}

DATABASE_ROUTERS = ['config.db_router.AppLabelRouter']


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'accounts.User'
LOGIN_URL = 'accounts:login'
LOGIN_REDIRECT_URL = 'index'
LOGOUT_REDIRECT_URL = 'index'
