# Generated by Django 6.0.6 on 2026-07-06 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('code', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=64)),
                ('symbols', models.JSONField(default=list)),
                ('is_native', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['display_name'],
            },
        ),
        migrations.CreateModel(
            name='LanguagePair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence_count', models.PositiveIntegerField(default=0)),
                ('native', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairs_as_native', to='infinitesentences.language')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairs_as_target', to='infinitesentences.language')),
            ],
            options={
                'ordering': ['native_id', 'target_id'],
                'unique_together': {('native', 'target')},
            },
        ),
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField()),
                ('text', models.TextField()),
                ('translations', models.JSONField(default=list)),
                ('credits', models.JSONField(default=list)),
                ('transcription', models.TextField(blank=True, default='')),
                ('pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentences', to='infinitesentences.languagepair')),
            ],
            options={
                'ordering': ['pair_id', 'index'],
                'unique_together': {('pair', 'index')},
            },
        ),
        migrations.CreateModel(
            name='SentencePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('content', models.TextField()),
                ('translations', models.JSONField(default=list)),
                ('usage_examples', models.JSONField(default=list)),
                ('transcription', models.TextField(blank=True, default='')),
                ('sentence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='infinitesentences.sentence')),
            ],
            options={
                'ordering': ['sentence_id', 'order'],
            },
        ),
    ]
