# Generated by Django 6.0.6 on 2026-07-06 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arz', models.TextField()),
                ('transliteration', models.TextField()),
                ('translations', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='ClozeWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=64)),
                ('distractors', models.JSONField()),
                ('sentence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cloze_words', to='egyptiansentences.sentence')),
            ],
            options={
                'ordering': ['sentence_id', 'id'],
            },
        ),
    ]
