# Generated by Django 6.0.6 on 2026-07-04 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clip',
            fields=[
                ('filename', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('transcript', models.TextField()),
                ('word_count', models.PositiveSmallIntegerField()),
                ('used_normalized_audio', models.BooleanField(default=False)),
            ],
        ),
    ]
