# Generated by Django 6.0.6 on 2026-07-18 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Background',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=8)),
                ('filename', models.CharField(max_length=255)),
                ('credit', models.TextField()),
            ],
            options={
                'ordering': ['language', 'id'],
                'indexes': [models.Index(fields=['language'], name='boringwords_languag_0065ad_idx')],
            },
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=8)),
                ('front', models.TextField()),
                ('back', models.TextField()),
                ('credit', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['language', 'id'],
                'indexes': [models.Index(fields=['language'], name='boringwords_languag_96135d_idx')],
            },
        ),
    ]
