# Generated by Django 6.0.6 on 2026-07-07 09:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=64)),
                ('event_type', models.CharField(max_length=64)),
                ('occurred_at', models.DateTimeField()),
                ('client_uuid', models.UUIDField(unique=True)),
                ('magnitude', models.FloatField(default=1)),
                ('payload', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'app_label', 'event_type', 'occurred_at'], name='tracking_ac_user_id_ca5cea_idx')],
            },
        ),
        migrations.CreateModel(
            name='LearningState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=64)),
                ('item_key', models.CharField(max_length=255)),
                ('state', models.JSONField()),
                ('updated_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_states', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'app_label', 'item_key'), name='unique_learning_state_item')],
            },
        ),
    ]
