# Generated by Django 6.0.6 on 2026-07-06 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlossTask',
            fields=[
                ('key', models.SlugField(max_length=64, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField(unique=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('code', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('audio_path', models.CharField(blank=True, max_length=255)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='prepositions3d.language')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='prepositions3d.glosstask')),
            ],
            options={
                'ordering': ['task_id', 'language_id'],
                'constraints': [models.UniqueConstraint(fields=('task', 'language'), name='unique_translation_per_task_language')],
            },
        ),
    ]
